# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSij <- function(expmu, expdelta, cdindex) {
    .Call('_BLPestimatoR_getSij', PACKAGE = 'BLPestimatoR', expmu, expdelta, cdindex)
}

getSjtMod <- function(expmu, expdelta, nprodt, startpos, weights) {
    .Call('_BLPestimatoR_getSjtMod', PACKAGE = 'BLPestimatoR', expmu, expdelta, nprodt, startpos, weights)
}

getExpMu <- function(theta2Matrix, qv, Xrandom, cdid, demographics) {
    .Call('_BLPestimatoR_getExpMu', PACKAGE = 'BLPestimatoR', theta2Matrix, qv, Xrandom, cdid, demographics)
}

getDelta <- function(theta2, deltaOld, cdid, cdindex, Xrandom, obsshare, innerCrit, innerMaxit, printLevel, indices, nodesRcMktShape, nodesDemMktShape, weights) {
    .Call('_BLPestimatoR_getDelta', PACKAGE = 'BLPestimatoR', theta2, deltaOld, cdid, cdindex, Xrandom, obsshare, innerCrit, innerMaxit, printLevel, indices, nodesRcMktShape, nodesDemMktShape, weights)
}

