# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSij <- function(expmu, expdelta, cdindex) {
    .Call('_BLPestimatoR_getSij', PACKAGE = 'BLPestimatoR', expmu, expdelta, cdindex)
}

getSjtMod <- function(expmu, expdelta, nprodt, startpos, weights) {
    .Call('_BLPestimatoR_getSjtMod', PACKAGE = 'BLPestimatoR', expmu, expdelta, nprodt, startpos, weights)
}

getExpMu <- function(theta2Matrix, qv, Xrandom, cdid, demographics) {
    .Call('_BLPestimatoR_getExpMu', PACKAGE = 'BLPestimatoR', theta2Matrix, qv, Xrandom, cdid, demographics)
}

getDelta <- function(theta2, deltaOld, cdid, cdindex, Xrandom, obsshare, innerCrit, innerMaxit, printLevel, indices, nodesRcMktShape, nodesDemMktShape, weights) {
    .Call('_BLPestimatoR_getDelta', PACKAGE = 'BLPestimatoR', theta2, deltaOld, cdid, cdindex, Xrandom, obsshare, innerCrit, innerMaxit, printLevel, indices, nodesRcMktShape, nodesDemMktShape, weights)
}

dstddelta_c <- function(sijt, weights) {
    .Call('_BLPestimatoR_dstddelta_c', PACKAGE = 'BLPestimatoR', sijt, weights)
}

dstdtheta_c <- function(sijt_arma, indices, xt_arma, qvt_arma, dt_arma, weights_arma) {
    .Call('_BLPestimatoR_dstdtheta_c', PACKAGE = 'BLPestimatoR', sijt_arma, indices, xt_arma, qvt_arma, dt_arma, weights_arma)
}

jacob_c <- function(sij, indices, blp_data, blp_parameters, blp_integration, printLevel) {
    .Call('_BLPestimatoR_jacob_c', PACKAGE = 'BLPestimatoR', sij, indices, blp_data, blp_parameters, blp_integration, printLevel)
}

